library(readxl)
library(gplots)
data<- read.csv('Costomer+OrderForm.csv')
View(data)
data2<- stack(data)
colnames(data2)<- c("Defective","Country")
View(data2)
attach(data2)
table(Defective,Country)
t2<- prop.table(table(Defective))
t1<- table(Country)
chisq.test(table(Defective,Country))
