install.packages('readxl')
library(readxl)
data<-read.csv('Cutlets.csv')
attach(data)
colnames(data)<-c("Unit1","Unit2")
View(data)
attach(data)
shapiro.test(Unit1)
shapiro.test(Unit2)
var.test(Unit1,Unit2)
t.test(Unit1,Unit2,alternative = "two.sided",conf.level = 0.95,correct = TRUE)
