library(readxl)
data<-read.csv('LabTAT.csv')
attach(data)
colnames(data)<-c("Laboratory1","Laboratory2","Laboratory3","Laboratory4")
View(data)
attach(data)
shapiro.test(Laboratory1)
shapiro.test(Laboratory2)
shapiro.test(Laboratory3)
shapiro.test(Laboratory4)
stack_data<- stack(data)
bartlett.test(values~ind,stack_data)
Anova_one_way<- aov(values~ind, data=stack_data)
summary(Anova_one_way)
